---
- name: Generate hosts file
  hosts: all
  become: true
  tasks:
    - name: download hosts.j2
      ansible.builtin.get_url:
        url: http://rhgls.labx.example.com/materials 
        dest: hosts.j2
      delegate_to: control
      ignore_errors: true

    - name: generate myhosts file
      ansible.builtin.template: 
        src: hosts.j2
        dest: /etc/myhosts
      when: "'database' in group_names"

